export const BASE_URL = "http://127.0.0.1:5000";

export const genres = [
  "Action",
  "Adventure",
  "Animation",
  "Children's",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Fantasy",
  "Film-Noir",
  "Horror",
  "Musical",
  "Mystery",
  "Romance",
  "Sci-Fi",
  "Thriller",
  "War",
  "Western",
];

export const occupations = [
  { display: "Other or Not Specified", value: "other or not specified" },
  { display: "Academic/Educator", value: "academic/educator" },
  { display: "Artist", value: "artist" },
  { display: "Clerical/Admin", value: "clerical/admin" },
  { display: "College/Grad Student", value: "college/grad student" },
  { display: "Customer Service", value: "customer service" },
  { display: "Doctor/Health Care", value: "doctor/health care" },
  { display: "Executive/Managerial", value: "executive/managerial" },
  { display: "Farmer", value: "farmer" },
  { display: "Homemaker", value: "homemaker" },
  { display: "K-12 Student", value: "K-12 student" },
  { display: "Lawyer", value: "lawyer" },
  { display: "Programmer", value: "programmer" },
  { display: "Retired", value: "retired" },
  { display: "Sales/Marketing", value: "sales/marketing" },
  { display: "Scientist", value: "scientist" },
  { display: "Self-Employed", value: "self-employed" },
  { display: "Technician/Engineer", value: "technician/engineer" },
  { display: "Tradesman/Craftsman", value: "tradesman/craftsman" },
  { display: "Unemployed", value: "unemployed" },
  { display: "Writer", value: "writer" },
];
